service: certificate

plugins:
  - serverless-offline

provider:
  name: aws

functions:
  hello:
    handler: src/functions/hello.handle
    events:
      - http:
        path: /hello
        method: GET
        cors: true